# 起動時のシェルをzsh
set-option -g default-shell /bin/zsh

# 256色表示
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# Wi-Fi、バッテリー残量、現在時刻
# 最右に表示
set-option -g status-right '#(wifi) #(get_battery_tmux) [%Y-%m-%d(%a) %H:%M]'
## 左パネルを設定する
set -g status-left-length 40
set -g status-left "#[fg=green]Session: #S #[fg=yellow]#I #[fg=cyan]#P "
## ステータスバーを上部に表示する
set -g status-position top

# ステータスバーの色を設定する
set -g status-fg white
set -g status-bg black

## ヴィジュアルノーティフィケーションを有効にする
set -g monitor-activity on
set -g visual-activity on

