#  _   _                  _                 _
# | | | |_   _ _ __  _ __| | __ _ _ __   __| |
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
# |  _  | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|
#
# -----------------------------------------------------


# ---
# Vars
# ---
source = ~/.config/hypr/config.d/00-vars.conf

# ---
# Monitor
# ---
source = ~/.config/hypr/config.d/10-monitor.conf

# ---
# Input
# ---
source = ~/.config/hypr/config.d/20-input.conf

# ---
# Key Binds
# ---
source = ~/.config/hypr/config.d/30-keybinds.conf
#source = ~/.config/hypr/config.d/31-keybinds-latest.conf

# ---
# Window rules
# ---
source = ~/.config/hypr/config.d/40-rules.conf

# ---
# Layout
# ---
source = ~/.config/hypr/config.d/50-layout.conf

# ---
# Appearance
# ---
source = ~/.config/hypr/config.d/60-appearance.conf

# ---
# Auto Start
# ---
source = ~/.config/hypr/config.d/90-autostart.conf
