source = ~/.config/hypr/config.d/00-vars.conf
source = ~/.config/hypr/config.d/10-monitor.conf
source = ~/.config/hypr/config.d/20-input.conf
source = ~/.config/hypr/config.d/30-keybinds.conf
source = ~/.config/hypr/config.d/40-rules.conf
source = ~/.config/hypr/config.d/50-appearance.conf
source = ~/.config/hypr/config.d/90-autostart.conf
