# boot apps
bindsym $mod+Return exec $term
bindsym $mod+D exec $menu

# kill / reload
bindsym $mod+Shift+Q kill
bindsym $mod+Shift+R reload
bindsym $mod+Shift+E exec swaynag -t warning -m "Exit?" -B "Yes" "swaymsg exit"

# focus
bindsym $mod+H focus left
bindsym $mod+J focus down
bindsym $mod+K focus up
bindsym $mod+L focus right

# move window
bindsym $mod+Shift+H move left
bindsym $mod+Shift+J move down
bindsym $mod+Shift+K move up
bindsym $mod+Shift+L move right

# workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5

bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5

# layout
bindsym $mod+F fullscreen toggle
bindsym $mod+Space floating toggle

# Sway
bindsym $mod+V splitv
bindsym $mod+Shift+V splith

# mouse
floating_modifier $mod normal

# screenshot
bindsym Print exec grim -g "$(slurp)" ~/Pictures/shot-$(date +%s).png
bindsym Shift+Print exec grim -g "$(slurp)" - | wl-copy

# sound
bindsym XF86AudioRaiseVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindsym XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindsym XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# light
bindsym XF86MonBrightnessUp exec brightnessctl set +5%
bindsym XF86MonBrightnessDown exec brightnessctl set 5%-
